#!/usr/bin/env node
// =============================================================================
// Build static site for GitHub Pages → docs/
// =============================================================================
const fs = require("fs");
const path = require("path");

const ROOT = __dirname;
const DOCS = path.join(ROOT, "docs");

// Clean
if (fs.existsSync(DOCS)) fs.rmSync(DOCS, { recursive: true });
fs.mkdirSync(DOCS, { recursive: true });

// 1. Bundle ALL template HTML into templates-data.js
var templates = [];
function scan(dir, prefix) {
  prefix = prefix || "";
  var entries = fs.readdirSync(dir, { withFileTypes: true });
  for (var e of entries) {
    if (e.isDirectory())
      scan(path.join(dir, e.name), prefix ? prefix + "/" + e.name : e.name);
    else if (e.name.endsWith(".html")) {
      var relPath = prefix ? prefix + "/" + e.name : e.name;
      var baseName = e.name.replace(".html", "");
      var category = "general";
      if (prefix.includes("member")) category = "member";
      else if (prefix.includes("manager")) category = "manager";
      else if (prefix.includes("layouts")) category = "layout";
      templates.push({
        id: relPath,
        name: baseName,
        category: category,
        path: relPath,
        content: fs.readFileSync(path.join(dir, e.name), "utf-8"),
      });
    }
  }
}
scan(path.join(ROOT, "templates"));
templates.sort(function (a, b) {
  var order = { layout: 0, general: 1, member: 2, manager: 3 };
  return (
    (order[a.category] || 9) - (order[b.category] || 9) ||
    a.name.localeCompare(b.name)
  );
});

// 2. Bundle layout, sample data, design, chicken corn, icons
var layout = fs.readFileSync(
  path.join(ROOT, "templates", "layouts", "base_layout.html"),
  "utf-8",
);
var sampleData = fs.existsSync(path.join(ROOT, "data", "sample_models.json"))
  ? fs.readFileSync(path.join(ROOT, "data", "sample_models.json"), "utf-8")
  : "{}";
var designDefault = fs.existsSync(path.join(ROOT, "config", "design.json"))
  ? fs.readFileSync(path.join(ROOT, "config", "design.json"), "utf-8")
  : "{}";
var chickenCorn = fs.existsSync(path.join(ROOT, "public", "chicken-corn.md"))
  ? fs.readFileSync(path.join(ROOT, "public", "chicken-corn.md"), "utf-8")
  : "";
var icons = fs.existsSync(path.join(ROOT, "public", "icons.json"))
  ? fs.readFileSync(path.join(ROOT, "public", "icons.json"), "utf-8")
  : "[]";

// 3. Write bundled data
var dataJs = `// Auto-generated by build.js – DO NOT EDIT
window.__TEMPLATES_DATA__ = ${JSON.stringify(templates)};
window.__LAYOUT_HTML__ = ${JSON.stringify(layout)};
window.__SAMPLE_DATA__ = ${sampleData};
window.__DESIGN_DEFAULT__ = ${designDefault.trim() || "{}"};
window.__CHICKEN_CORN__ = ${JSON.stringify(chickenCorn)};
window.__ICONS_DATA__ = ${icons};
`;
fs.writeFileSync(path.join(DOCS, "data.js"), dataJs);

// 4. Copy styles
fs.copyFileSync(
  path.join(ROOT, "public", "styles.css"),
  path.join(DOCS, "styles.css"),
);

// 5. Copy static index.html (GitHub Pages entry point)
fs.copyFileSync(
  path.join(ROOT, "public", "pages-index.html"),
  path.join(DOCS, "index.html"),
);

// 6. Write static app.js (copy for reference, main logic is inline in index.html)
var appJs = fs.readFileSync(path.join(ROOT, "public", "app.js"), "utf-8");
fs.writeFileSync(path.join(DOCS, "app-static.js"), appJs);

console.log("✅ Built docs/ with " + templates.length + " templates");
console.log("   Files: index.html, data.js, app-static.js, styles.css");
